List userList = [
  {
    'avatar': 'assets/images/profile.png',
    'name': 'Tunji Chibuike',
    'class': 'Nursery Class',
    'accept': 'assets/images/accept.png',
    'reject': 'assets/images/reject.png',
  },
  {
    'avatar': 'assets/images/profile.png',
    'name': 'Tunji Doe',
    'class': 'Primary Class',
    'accept': 'assets/images/accept.png',
    'reject': 'assets/images/reject.png',
  },
  {
    'avatar': 'assets/images/profile.png',
    'name': 'Tunji Samson',
    'class': 'Nursery Class',
    'accept': 'assets/images/accept.png',
    'reject': 'assets/images/reject.png',
  },
  {
    'avatar': 'assets/images/profile.png',
    'name': 'Justin Moore',
    'class': 'Nursery Class',
    'accept': 'assets/images/accept.png',
    'reject': 'assets/images/reject.png',
  },
  {
    'avatar': 'assets/images/profile.png',
    'name': 'Paul Jones',
    'class': 'Nursery Class',
    'accept': 'assets/images/accept.png',
    'reject': 'assets/images/reject.png',
  },
  {
    'avatar': 'assets/images/profile.png',
    'name': 'Smith Cole',
    'class': 'Nursery Class',
    'accept': 'assets/images/accept.png',
    'reject': 'assets/images/reject.png',
  },
  {
    'avatar': 'assets/images/profile.png',
    'name': 'Carl Moore',
    'class': 'Primary Class',
    'accept': 'assets/images/accept.png',
    'reject': 'assets/images/reject.png',
  },
  {
    'avatar': 'assets/images/profile.png',
    'name': 'Paul Smith',
    'class': 'Nursery Class',
    'accept': 'assets/images/accept.png',
    'reject': 'assets/images/reject.png',
  },
  {
    'avatar': 'assets/images/profile.png',
    'name': 'Sean Cole',
    'class': 'Primary Class',
    'accept': 'assets/images/accept.png',
    'reject': 'assets/images/reject.png',
  },
  {
    'avatar': 'assets/images/profile.png',
    'name': 'Caleb John',
    'class': 'Science Class',
    'accept': 'assets/images/accept.png',
    'reject': 'assets/images/reject.png',
  },
];


List scheduleList = [
  {
    'avatar': 'assets/images/profile.png',
    'name': 'Tunji Chibuike',
    'date': 'Wednesday, 23 June 2021',
    'time': '4:00PM',
  },
  {
    'avatar': 'assets/images/profile.png',
    'name': 'Tunji Doe',
    'date': 'Tuesday, 23 June 2021',
    'time': '4:00PM',
  },
  {
    'avatar': 'assets/images/profile.png',
    'name': 'Tunji Samson',
    'date': 'Wednesday, 23 June 2021',
    'time': '4:00PM',
  },
  {
    'avatar': 'assets/images/profile.png',
    'name': 'Justin Moore',
    'date': 'Wednesday, 23 June 2021',
    'time': '4:00PM',
  },
  {
    'avatar': 'assets/images/profile.png',
    'name': 'Paul Jones',
    'date': 'Friday, 23 June 2021',
    'time': '4:00PM',
  },
  {
    'avatar': 'assets/images/profile.png',
    'name': 'Smith Cole',
    'date': 'Wednesday, 23 June 2021',
    'time': '4:00PM',
  },
  {
    'avatar': 'assets/images/profile.png',
    'name': 'Carl Moore',
    'date': 'Thursday, 23 June 2021',
    'time': '4:00PM',
  },
  {
    'avatar': 'assets/images/profile.png',
    'name': 'Paul Smith',
    'date': 'Sunday, 23 June 2021',
    'time': '4:00PM',
  },
  {
    'avatar': 'assets/images/profile.png',
    'name': 'Sean Cole',
    'date': 'Wednesday, 23 June 2021',
    'time': '4:00PM',
  },
  {
    'avatar': 'assets/images/profile.png',
    'name': 'Caleb John',
    'date': 'Friday, 23 June 2021',
    'time': '4:00PM',
  },
];